### ISSUE TITLE
Example fails to retreive user's anime list.

### ISSUE THREAD

**Issue by dance2die** [LHCGreg/mal-api#1]
When running an example, it fails to complete due to an illegal XML return data from MAL.

Instead of returning XML data, it returns an HTML page that seems to be used to block robots.

![malapi example issue](https://cloud.githubusercontent.com/assets/8465237/6281257/44e010d2-b88b-11e4-8d7a-c985358d0b04.png)

**Comment by dance2die** [comment]
To get around the problem above, before calling "api.GetAnimeListForUser(...)", I changed User Agent to that of a Chrome. Now the first part (api.GetAnimeListForUser) works.

Now the problem is the second call, "api.GetRecentOnlineUsers".  For some reason, even with Chrome's UserAgent, "http://myanimelist.net/users.php" returns an HTML string banning robots...

**Comment by dance2die** [comment]
Closed the issue by mistake...

**Comment by dance2die** [comment]
To get around the problem above, before calling "api.GetAnimeListForUser(...)", I changed User Agent to that of a Chrome. Now the first part (api.GetAnimeListForUser) works.

Now the problem is the second call, "api.GetRecentOnlineUsers".  For some reason, even with Chrome's UserAgent, "http://myanimelist.net/users.php" returns an HTML string banning robots...

**Comment by LHCGreg** [comment]
Thanks for checking out this project. To get your program unblocked you can go to http://myanimelist.net/forum/?topicid=692311&show=0 and fill out the form linked there. If MAL accepts your request to be whitelisted, you'll be given an alphanumeric key. Set the UserAgent property to that key and you'll stop getting incapsula garbage instead of the data you want. Good luck, I had to wait quite a while to get whitelisted.

**Comment by dance2die** [comment]
Thanks, LHCGreg. I applied to get whitelisted.
I am having fun learning how to access web api from your code.
Keep up the good work~
